on: push
name: TOC Generator

jobs:
  toc:
    if: github.event.pull_request.head.user.id == github.event.pull_request.base.user.id
    name: TOC Generator
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: technote-space/toc-generator@v4.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
